const answers = [
    "A mousetrap",
    "Lincoln",
    "Reagan",
    "George W. Bush",
    "Obama",
    "A corpse",
    "A church",
    "A blessing",
    "Mice",
    "A hunting license",
    "ABC, Always Be Coding.",
    "For sure.",
    "I can't get my site to deploy.",
    "It works on my computer.",
    "Make a function.",
    "Google Fu",
    "A typo.",
    "Forgetting to save.",
    "CD into the folder.",
    "React.js",
    "JavaScript",
    "MySQL",
    "HTML",
    "CSS",
    "Node.js",
    "Because he didn't get arrays.",
    "Why i?",
    "ABS, Always Be Saving.",
    "Mac",
    "Linux",
    "Windows",
    "MongoDB",
    "MERN Stack",
    "Express.js",
    "Crying forever.",
    "Procrastinating.",
    "Sobbing uncontrollably.",
    "Pulling an all nighter.",
    "All the coffee in the world.",
    "Me singing in the shower.",
    "Infinite tacos.",
    "Your keyboard dying in the middle of a presentation.",
    "Mom's Spaghetti.",
    "Code nightmares.",
    "You're on mute"
    ]

export default answers;