const answers = [
    "ABC, Always Be Coding.",
    "For sure.",
    "I can't get my site to deploy.",
    "It works on my computer.",
    "Make a function.",
    "Google Fu",
    "A typo.",
    "Forgetting to save.",
    "CD into the folder.",
    "React.js",
    "JavaScript",
    "MySQL",
    "HTML",
    "CSS",
    "Node.js",
    "Why i?",
    "ABS, Always Be Saving.",
    "Mac",
    "Linux",
    "Windows",
    "MongoDB",
    "MERN Stack",
    "Express.js",
    "Crying forever.",
    "Procrastinating.",
    "Sobbing uncontrollably.",
    "Pulling an all nighter.",
    "All the coffee in the world.",
    "Infinite tacos.",
    "Your keyboard dying in the middle of a presentation.",
    "Mom's Spaghetti.",
    "Code nightmares.",
    "You're on mute",
    "Sommer's apples",
    "Discord Gifs",
    "Divide and conquer",
    "Percy",
    "Gemini's Pig",
    "Share your screen",
    "Mary Poppins",
    "Bagged Milk",
    "Show Me",
    "Doge Coin",
    "The Discord Server",
    "Optional Homework",
    "Spongebob",
    "Help in room 2",
    "Drag them!",
    "JJ the Jetplane",
    ]

module.exports = answers;