const cahA = [
"10,000 Syrian refugees.",
"400 years of colonial atrocities.",
"50,000 volts straight to the nipples.",
"72 virgins.",
"8 oz. of sweet Mexican black-tar heroin.",
"A bag of magic beans.",
"A balanced breakfast.",
"A ball of earwax, semen, and toenail clippings.",
"A bird that shits human turds.",
"A bit of slap and tickle.",
"A bitch slap.",
"A bleached arsehole.",
"A bowl of mayonnaise and human teeth.",
"A brain tumour.",
"A comprehensive understanding of the Irish backstop.",
"A crucifixion.",
"A deep-rooted fear of the working class.",
"A disappointing birthday party.",
"A falcon with a cap on its head.",
"A fanny fart.",
"A fart so powerful that it wakes the giants from their thousand-year slumber.",
"A Fleshlight®.",
"A foetus.",
"A fuck-tonne of almonds.",
"A general lack of purpose.",
"A Ginsters pasty and three cans of Monsters Energy.",
"A good sniff.",
"A good, strong gorilla.",
"A gossamer stream of jizz that catches the light as it arcs through the morning air.",
"A hen night in Slough.",
"A homoerotic volleyball montage.",
"A horde of Vikings.",
"A lifetime of sadness.",
"A little boy who won't shut the fuck up about dinosaurs.",
"A live studio audience.",
"A man on the brink of orgasm.",
"A meat raffle!",
"A micropenis.",
"A micropig wearing a tiny raincoat and booties.",
"A middle-aged man on roller skates.",
"A mopey zoo lion.",
"A much younger woman.",
"A nice cup of tea.",
"A pangender octopus who roams the cosmos in search of love.",
"A posh wank.",
"A pyramid of severed heads.",
"A really cool hat.",
"A sad handjob.",
"A salad for men that's made of metal.",
"A salty surprise.",
"A saxophone solo.",
"A sea of troubles.",
"A slightly salty toad in the hole.",
"A snapping turtle biting the tip of your penis.",
"A sober Irishman who doesn't care for potatoes.",
"A stray pube.",
"A Super Soaker™ full of cat pee.",
"A time travel paradox.",
"A tiny horse.",
"A vindaloo poo.",
"A white ethnostate.",
"A white van man.",
"A windmill full of corpses.",
"Academy Award winner Meryl Streep.",
"Accepting the way things are.",
"African children.",
"Agriculture.",
"AIDS.",
"Ainsley Harriott.",
"Alcoholism.",
"All my gentleman suitors.",
"All the dudes I've fucked.",
"An AK-47 assault rifle.",
"An endless stream of diarrhoea.",
"An erection that lasts longer than four hours.",
"An M. Night Shyamalan plot twist.",
"An octopus giving seven handjobs and smoking a cigarette.",
"An Oedipus complex.",
"An old guy who's almost dead.",
"An older woman who knows her way around the penis.",
"An oversized lollipop.",
"An unwanted pregnancy.",
"Anal beads.",
"Announcing that I am about to cum.",
"Arnold Schwarzenegger.",
"Auschwitz.",
"Autocannibalism.",
"Balls.",
"Bananas.",
"Barack Obama.",
"Barely making £15,000 a year.",
"BATMAN!",
"Battlefield amputations.",
"Becoming a blueberry.",
"Bees?",
"Being a dick to children.",
"Being a motherfucking sorcerer.",
"Being a witch.",
"Being a woman.",
"Being able to talk to elephants.",
"Being fucking stupid.",
"Being marginalised.",
"Being on fire.",
"Being rich.",
"Bitches.",
"Black people.",
"Blood, sweat, and tears.",
"Blowing my boyfriend so hard he shits.",
"Blowing up Parliament.",
"Bogies.",
"Boris Johnson.",
"Braiding three penises into a Curly Wurly.",
"Breaking out into song and dance.",
"Brexit.",
"Brown people.",
"Brutal austerity.",
"Bubble butt bottom boys.",
"Cards Against Humanity.",
"Casually suggesting a threesome.",
"Catapults.",
"Chainsaws for hands.",
"Cheeky bum sex.",
"Chemical weapons.",
"Child abuse.",
"Child beauty pageants.",
"Chunks of dead hitchhiker.",
"Coat hanger abortions.",
"Committing suicide.",
"Completely unwarranted confidence.",
"Consensual sex.",
"Cottaging.",
"Crippling debt.",
"Crumbs all over the bloody carpet.",
"Cuddling.",
"Cunnilingus.",
"Daddies® Brown Sauce.",
"Daddy issues.",
"Daniel Radcliffe's delicious arsehole.",
"Danny DeVito.",
"Danny Dyer.",
"Dark and mysterious forces beyond our control.",
"Darth Vader.",
"David Bowie flying in on a tiger made of lightning.",
"Dead babies.",
"Dead birds everywhere.",
"Dead parents.",
"Denying climate change.",
"Dick fingers.",
"Dick pics.",
"Dirty nappies.",
"Discovering he's a Tory.",
"Diversity.",
"Dogging.",
"Doing crimes.",
"Doing the right thing.",
"Donald J. Trump.",
"Drinking alone.",
"Drinking out of the toilet and eating rubbish.",
"Drowning the kids in the bathtub.",
"Dry heaving.",
"Dwayne 'The Rock' Johnson.",
"Dying.",
"Eating a hard boiled egg out of my husband's arsehole.",
"Ecstasy.",
"Egging an MP.",
"Elderly Japanese men.",
"Emerging from the sea and rampaging through Tokyo.",
"Emotions.",
"England.",
"Erectile dysfunction.",
"Establishing dominance.",
"Ethnic cleansing.",
"Exactly what you'd expect.",
"Executing a hostage every hour.",
"Expecting a burp and vomiting on the floor.",
"Explaining how vaginas work.",
"Explosions.",
"Extremely tight trousers.",
"Fading away into nothingness.",
"Faffing about.",
"Fake tits.",
"Famine.",
"Farting and walking away.",
"Fear itself.",
"Fellowship in Christ.",
"Filling my briefcase with business stuff.",
"Finger painting.",
"Firing a rifle into the air while balls deep in a squealing hog.",
"Flat out not giving a shit.",
"Flesh-eating bacteria.",
"Flightless birds.",
"Flying sex snakes.",
"Forced sterilisation.",
"Foreskin.",
"Fragile masculinity.",
"Free samples.",
"Friction.",
"Fucking my sister.",
"Fucking the weatherman on live television.",
"Full frontal nudity.",
"Gandhi.",
"Gay conversion therapy.",
"Geese.",
"Genuine human connection.",
"German Chancellor Angela Merkel.",
"German dungeon porn.",
"Getting crushed by a vending machine.",
"Getting cummed on.",
"Getting drugs off the street and into my body.",
"Getting fingered.",
"Getting married, having a few kids, buying some stuff, retiring to the south of France, and dying.",
"Getting naked and watching CBeebies.",
"Getting really high.",
"Getting the same Boots Meal Deal every day for six years.",
"Ghosts.",
"Girls.",
"Giving 110%.",
"Giving birth to the Antichrist.",
"Gloryholes.",
"Goblins.",
"God.",
"Going an entire day without masturbating.",
"Grandma.",
"Harry Potter erotica.",
"Having anuses for eyes.",
"Having big dreams but no realistic way to achieve them.",
"Having sex for the first time.",
"Heartwarming orphans.",
"Her Majesty, Queen Elizabeth II.",
"Hobos.",
"Holding down a child and farting all over him.",
"Hope.",
"Horse meat.",
"Hospice care.",
"Hot cheese.",
"Hot people.",
"How bad my daughter fucked up her dance recital.",
"How far I can get my own penis up my butt.",
"However much weed £20 can buy.",
"Huge biceps.",
"Hurting those closest to me.",
"Illegal immigrants.",
"Inappropriate yodeling.",
"Incest.",
"Inserting a Mason jar into my anus.",
"Invading Poland.",
"Italians.",
"Itchy pussy.",
"James fucking Cordon.",
"Jennifer Lawrence.",
"Jews, gypsies, and homosexuals.",
"Jimmy Savile.",
"Jobs.",
"Judging everyone.",
"Justin Bieber.",
"Kamikaze pilots.",
"Kissing nan on the forehead and turning off her life support.",
"Knife crime.",
"Kourtney, Kim, Khloe, Kendall, and Kylie.",
"Lactation.",
"Lads.",
"Land mines.",
"Laying an egg.",
"Leprosy.",
"Licking the Queen.",
"Licking things to claim them as your own.",
"Listening to her problems without trying to solve them.",
"Little boy penises.",
"Looking in the mirror, applying lipstick, and whispering 'tonight, you will have sex with Tom Cruise.'",
"Lumberjack fantasies.",
"LYNX® Body Spray.",
"Mad cow disease.",
"Madeleine McCann.",
"Magnets.",
"Making a pouty face.",
"Man meat.",
"Many bats.",
"Martin Lewis, Money Saving Expert.",
"Masturbating.",
"Maureen of Blackpool, Reader's Wife of the Year 1988.",
"Me time.",
"Memes.",
"Men discussing their feelings in an emotionally healthy way.",
"Men.",
"Menstrual rage.",
"Meth.",
"More elephant cock than I bargained for.",
"Morgan Freeman's voice.",
"Mouth herpes.",
"Muhammad (Peace Be Upon Him).",
"Multiple stab wounds.",
"Murder.",
"Mutually assured destruction.",
"My abusive boyfriend who really isn't so bad once you get to know him.",
"My balls on your face.",
"My bright pink fuckhole.",
"My cheating prick of a husband.",
"My collection of Japanese sex toys.",
"My ex-wife.",
"My fat daughter.",
"My genitals.",
"My good bra.",
"My inner demons.",
"My little boner.",
"My mate Dave.",
"My neck, my back, my pussy, and my crack.",
"My relationship status.",
"My sex life.",
"My soul.",
"My Uber driver, Ajay.",
"My ugly face and bad personality.",
"My vagina.",
"Natural male enhancement.",
"Natural selection.",
"Nazis.",
"Necrophilia.",
"Nicki Minaj.",
"Nicolas Cage.",
"Nipple blades.",
"Not giving a shit about the Third World.",
"Not reciprocating oral sex.",
"Not wearing trousers.",
"Object permanence.",
"Oestrogen.",
"Old-people smell.",
"One titty hanging out.",
"One trillion dollars.",
"Only dating Asian women.",
"Oompa-Loompas.",
"Opposable thumbs.",
"Pac-Man uncontrollably guzzling cum.",
"Paedophiles.",
"Passive-aggressive Post-it notes.",
"Peeing a little bit.",
"Penis breath.",
"Penis envy.",
"Permanent Orgasm-Face Disorder.",
"Pictures of boobs.",
"Pixelated bukkake.",
"Police brutality.",
"Polish People.",
"Pooping back and forth. Forever.",
"Pooping in a laptop and closing it.",
"Poor life choices.",
"Poor people.",
"Poorly-timed Holocaust jokes.",
"Poverty.",
"Powerful thighs.",
"Preteens.",
"Pretending to care.",
"PTSD.",
"Puberty.",
"Pulling out.",
"Puppies!",
"Putting things where they go.",
"Queen Elizabeth's immaculate anus.",
"Queuing.",
"Racism.",
"Radical Islamic terrorism.",
"Raptor attacks.",
"Rectangles.",
"Repression.",
"RoboCop.",
"Running out of semen.",
"Ryanair.",
"Saying 'I love you.'",
"Science.",
"Scottish independence.",
"Scousers.",
"Seeing Granny naked.",
"Seeing my father cry.",
"Seeing what happens when you lock people in a room with hungry seagulls.",
"Seething with quiet resentment.",
"Self-loathing.",
"Selling crack to children.",
"Seppuku.",
"Serfdom.",
"Seven dead and three in critical condition.",
"Sex with animals.",
"Sex with Patrick Stewart.",
"Sexual peeing.",
"Sexual tension.",
"Shapeshifters.",
"Shiny objects.",
"Shitting out a perfect Cumberland sausage.",
"Shutting up so I can watch the match.",
"Sideboob.",
"Silence.",
"Sitting in a jar of vinegar all night because I am gherkin.",
"Sitting on my face.",
"Slapping Nigel Farage over and over.",
"Slapping your knees to signal your imminent departure.",
"Slaughtering innocent civilians.",
"Smegma.",
"Sniffing and kissing my feet.",
"Sniffing glue.",
"Soft, kissy missionary sex.",
"Solving problems with violence.",
"Somali pirates.",
"Some bloody peace and quiet.",
"Some foundation, mascara, and a touch of blush.",
"Some guy.",
"Soup that is too hot.",
"Spaghetti? Again?",
"Spaniards.",
"Spectacular abs.",
"Sperm whales.",
"Spontaneous human combustion.",
"Stalin.",
"Still being a virgin.",
"Strong female characters.",
"Sunshine and rainbows.",
"Sweet, sweet vengeance.",
"Swooping.",
"Synergistic management solutions.",
"Tap dancing like there's no tomorrow.",
"Teaching a robot to love.",
"Teenage pregnancy.",
"Telling a shitty story that goes nowhere.",
"Tentacle porn.",
"The American Dream.",
"The arrival of the pizza.",
"The bastard seagull who stole my chips.",
"The Big Bang.",
"The Black Death.",
"The Blood of Christ.",
"The bombing of Nagasaki.",
"The clitoris.",
"The cool, refreshing taste of Pepsi®.",
"The Daily Mail.",
"The Devil Himself.",
"The end of days.",
"The female orgasm.",
"The Force.",
"The French.",
"The gays.",
"The glass ceiling.",
"The Great Depression.",
"The guys from Queer Eye.",
"The heart of a child.",
"The Holy Bible.",
"The homosexual agenda.",
"The illusion of choice in a late-stage capitalist society.",
"The inevitable heat death of the universe.",
"The Jews.",
"The KKK.",
"The magic of live theatre.",
"The milkman.",
"The miracle of childbirth.",
"The North.",
"The only gay person in a hundred miles.",
"The past.",
"The Patriarchy.",
"The penny whistle solo from 'My Heart Will Go On.'",
"The petty troubles of the aristrocracy.",
"The placenta.",
"The Pope.",
"The rhythms of Africa.",
"The Russians.",
"The Scouts.",
"The screams...the terrible screams.",
"The Smell of a Primark.",
"The Strictly Come Dancing final.",
"The true meaning of Christmas.",
"The unstoppable tide of Islam.",
"The violation of our most basic human rights.",
"The way James Bond treats women.",
"The Welsh.",
"The wifi password.",
"Therapy.",
"Three dicks at the same time.",
"Throwing a virgin into a volcano.",
"Throwing grapes at a man until he loses touch with reality.",
"Tories.",
"Touching a pug right on his penis.",
"Trench foot.",
"Unfathomable stupidity.",
"Used knickers.",
"Viagra®.",
"Vigorous jazz hands.",
"Vladimir Putin.",
"Vomiting seafood and bleeding anally.",
"Waiting till marriage.",
"Waking up half-naked in a Wetherspoons car park.",
"Waking up in Idris Elba's arms.",
"Wanking into a pool of children's tears.",
"Wet dreams.",
"What that mouth do.",
"Whipping it out.",
"White people.",
"White privilege.",
"William Shatner.",
"Wizard music.",
"Women in yoghurt commercials.",
"Women's suffrage.",
"World peace.",
"Worshipping that pussy.",
"Yeast.",
"Your mum.",
"Your weird brother."
]

module.exports = cahA; 