const cahQ = [
  "______: kid-tested, mother-approved.",
  "______. It's a trap!",
  "______. That was so metal.",
  "50% of all marriages end in ______.",
  "A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ______.",
  "A romantic, candlelit dinner would be incomplete without ______.",
  "After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.",
  "Alternative medicine is now embracing the curative powers of ______.",
  "But before I kill you, Mr. Bond, I must show you ______.",
  "Check me out, yo! I call this dance move '______.'",
  "Click Here for ______!!!",
  "During sex, I like to think about ______.",
  "Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.",
  "Here is the church, Here is the steeple, Open the doors, And there is ______.",
  "Hey Reddit! I'm ______. Ask me anything.",
  "How did I lose my virginity?",
  "I drink to forget ______.",
  "I get by with a little help from ______.",
  "I got 99 problems but ______ ain't one.",
  "I'm going on a cleanse this week. Nothing but kale juice and ______.",
  "I'm no doctor, but I'm pretty sure what you're suffering from is called '______.'",
  "If you can't be with the one you love, love ______.",
  "It’s a pity that kids these days are all getting involved with ______.",
  "Just saw this upsetting video! Please retweet!! #stop______",
  "Kids, I don't need drugs to get high. I'm high on ______.",
  "Life for American Indians was forever changed when the White Man introduced them to ______.",
  "Maybe she's born with it. Maybe it's ______.",
  "Military historians remember Alexander the Great for his brilliant use of ______ against the Persians.",
  "Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ______?",
  "Next from J.K. Rowling: Harry Potter and the Chamber of ______.",
  "Old MacDonald had ______. E-I-E-I-O.",
  "'This is the way the world ends",
  "Not with a bang but with ______.'",
  "Uh, hey guys, I know this was my idea, but I'm having serious doubts about ______.",
  "War! What is it good for?",
  "Well if you'll excuse me, gentlemen, I have a date with ______.",
  "What are my parents hiding from me?",
  "What ended my last relationship?",
  "What gives me uncontrollable gas?",
  "What is Batman's guilty pleasure?",
  "What is George W. Bush thinking about right now?",
  "What made my first kiss so awkward?",
  "What makes life worth living?",
  "What never fails to liven up the party?",
  "What will always get you laid?",
  "What would grandma find disturbing, yet oddly charming?",
  "What's a girl's best friend?",
  "What's my secret power?",
  "What's that smell?",
  "What's that sound?",
  "What's there a ton of in heaven?",
  "When I am a billionare, I shall erect a 50-foot statue to commemorate ______.",
  "When Pharaoh remained unmoved, Moses called down a Plague of ______.",
  "White people like ______.",
  "Why am I sticky?",
  "Why can't I sleep at night?",
  "Why do I hurt all over?"
]

module.exports = cahQ;